"""add visual generation fields and versions

Revision ID: 0ad6c6bf16c6
Revises: 3b52036be01a
Create Date: 2026-06-18 15:13:07.158773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad6c6bf16c6'
down_revision: Union[str, None] = '3b52036be01a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual_versions',
    sa.Column('visual_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=2048), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['visual_id'], ['generated_visuals.id'], name=op.f('fk_visual_versions_visual_id_generated_visuals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visual_versions'))
    )
    with op.batch_alter_table('visual_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visual_versions_visual_id'), ['visual_id'], unique=False)

    with op.batch_alter_table('generated_visuals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visual_kind', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('generation_method', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('file_format', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('slide_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_generated_visuals_visual_kind'), ['visual_kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_visuals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_visuals_visual_kind'))
        batch_op.drop_column('status')
        batch_op.drop_column('version')
        batch_op.drop_column('slide_number')
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('file_format')
        batch_op.drop_column('generation_method')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('visual_kind')

    with op.batch_alter_table('visual_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visual_versions_visual_id'))

    op.drop_table('visual_versions')
    # ### end Alembic commands ###
