"""add review feedback tables and fields

Revision ID: 11f44247c0d5
Revises: 0ad6c6bf16c6
Create Date: 2026-06-18 21:28:03.812740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f44247c0d5'
down_revision: Union[str, None] = '0ad6c6bf16c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regeneration_plans',
    sa.Column('review_session_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], name=op.f('fk_regeneration_plans_review_session_id_review_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regeneration_plans'))
    )
    with op.batch_alter_table('regeneration_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regeneration_plans_review_session_id'), ['review_session_id'], unique=False)

    op.create_table('review_notifications',
    sa.Column('review_session_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], name=op.f('fk_review_notifications_review_session_id_review_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_notifications'))
    )
    with op.batch_alter_table('review_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_notifications_review_session_id'), ['review_session_id'], unique=False)

    op.create_table('review_packages',
    sa.Column('review_session_id', sa.Uuid(), nullable=False),
    sa.Column('newsletter_id', sa.Uuid(), nullable=False),
    sa.Column('package', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], name=op.f('fk_review_packages_newsletter_id_newsletters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], name=op.f('fk_review_packages_review_session_id_review_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_packages'))
    )
    with op.batch_alter_table('review_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_packages_newsletter_id'), ['newsletter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_packages_review_session_id'), ['review_session_id'], unique=True)

    op.create_table('review_versions',
    sa.Column('newsletter_id', sa.Uuid(), nullable=False),
    sa.Column('review_session_id', sa.Uuid(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('feedback_summary', sa.JSON(), nullable=True),
    sa.Column('regeneration_plan', sa.JSON(), nullable=True),
    sa.Column('changed_sections', sa.JSON(), nullable=True),
    sa.Column('reviewer_decision', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], name=op.f('fk_review_versions_newsletter_id_newsletters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], name=op.f('fk_review_versions_review_session_id_review_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_versions'))
    )
    with op.batch_alter_table('review_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_versions_newsletter_id'), ['newsletter_id'], unique=False)

    with op.batch_alter_table('feedback_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artifact_type', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('section_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('feedback_category', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('action_required', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('regeneration_needed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('review_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_state', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('notion_page_url', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('version_number', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_review_sessions_review_state'), ['review_state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_sessions_review_state'))
        batch_op.drop_column('version_number')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('notion_page_url')
        batch_op.drop_column('review_state')

    with op.batch_alter_table('feedback_items', schema=None) as batch_op:
        batch_op.drop_column('regeneration_needed')
        batch_op.drop_column('action_required')
        batch_op.drop_column('severity')
        batch_op.drop_column('feedback_category')
        batch_op.drop_column('section_name')
        batch_op.drop_column('artifact_type')

    with op.batch_alter_table('review_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_versions_newsletter_id'))

    op.drop_table('review_versions')
    with op.batch_alter_table('review_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_packages_review_session_id'))
        batch_op.drop_index(batch_op.f('ix_review_packages_newsletter_id'))

    op.drop_table('review_packages')
    with op.batch_alter_table('review_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_notifications_review_session_id'))

    op.drop_table('review_notifications')
    with op.batch_alter_table('regeneration_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regeneration_plans_review_session_id'))

    op.drop_table('regeneration_plans')
    # ### end Alembic commands ###
