"""initial schema with collection fields

Revision ID: 250f42812eb5
Revises: 
Create Date: 2026-06-17 12:39:07.953777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250f42812eb5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_categories'))
    )
    with op.batch_alter_table('article_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_categories_name'), ['name'], unique=True)

    op.create_table('content_sources',
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('rss', 'blog', 'website', 'documentation', 'research', 'benchmark', 'newsletter', 'trend_signal', 'enterprise_report', name='source_type', native_enum=False, length=50), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('rss_url', sa.String(length=2048), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('best_use', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('preferred_collection_method', sa.Enum('rss', 'web', 'documentation', 'research', 'newsletter', name='preferred_collection_method', native_enum=False, length=50), nullable=False),
    sa.Column('fallback_collection_method', sa.Enum('rss', 'web', 'documentation', 'research', 'newsletter', name='fallback_collection_method', native_enum=False, length=50), nullable=True),
    sa.Column('newsletter_section', sa.Enum('Agentic AI Engineering', 'AI Evaluation & QA Gates', 'AI Testing & Quality Engineering', 'Enterprise AI Adoption', 'AI Tools Worth Watching', 'Research Watch', 'Coding Agent Benchmark Watch', 'Weekly Trend Signals', name='source_newsletter_section', native_enum=False, length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_sources'))
    )
    with op.batch_alter_table('content_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_sources_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_sources_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_sources_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_sources_source_type'), ['source_type'], unique=False)

    op.create_table('newsletters',
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'review', 'approved', 'published', 'archived', name='newsletter_status', native_enum=False, length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletters'))
    )
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletters_issue_number'), ['issue_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_newsletters_status'), ['status'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'editor', 'reviewer', 'viewer', name='user_role', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('collected_articles',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'processed', 'duplicate', 'failed', name='article_status', native_enum=False, length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('source_priority', sa.Integer(), nullable=True),
    sa.Column('source_category', sa.String(length=120), nullable=True),
    sa.Column('newsletter_section', sa.Enum('Agentic AI Engineering', 'AI Evaluation & QA Gates', 'AI Testing & Quality Engineering', 'Enterprise AI Adoption', 'AI Tools Worth Watching', 'Research Watch', 'Coding Agent Benchmark Watch', 'Weekly Trend Signals', name='article_newsletter_section', native_enum=False, length=64), nullable=True),
    sa.Column('collection_method', sa.Enum('rss', 'web', 'documentation', 'research', 'newsletter', name='article_collection_method', native_enum=False, length=50), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=True),
    sa.Column('freshness_score', sa.Float(), nullable=True),
    sa.Column('relevance_hint', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['article_categories.id'], name=op.f('fk_collected_articles_category_id_article_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], name=op.f('fk_collected_articles_source_id_content_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collected_articles')),
    sa.UniqueConstraint('url', name=op.f('uq_collected_articles_url'))
    )
    with op.batch_alter_table('collected_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collected_articles_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collected_articles_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_collected_articles_published_date'), ['published_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_collected_articles_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collected_articles_status'), ['status'], unique=False)

    op.create_table('generated_visuals',
    sa.Column('newsletter_id', sa.Uuid(), nullable=False),
    sa.Column('visual_type', sa.Enum('hero', 'section', 'social', name='visual_type', native_enum=False, length=50), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], name=op.f('fk_generated_visuals_newsletter_id_newsletters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_visuals'))
    )
    with op.batch_alter_table('generated_visuals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_visuals_newsletter_id'), ['newsletter_id'], unique=False)

    op.create_table('newsletter_sections',
    sa.Column('newsletter_id', sa.Uuid(), nullable=False),
    sa.Column('section_name', sa.String(length=255), nullable=True),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], name=op.f('fk_newsletter_sections_newsletter_id_newsletters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_sections'))
    )
    with op.batch_alter_table('newsletter_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_sections_newsletter_id'), ['newsletter_id'], unique=False)

    op.create_table('publication_records',
    sa.Column('newsletter_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('beehiiv', 'linkedin', 'email', name='publication_channel', native_enum=False, length=50), nullable=False),
    sa.Column('publication_status', sa.Enum('pending', 'scheduled', 'published', 'failed', name='publication_status', native_enum=False, length=50), nullable=False),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], name=op.f('fk_publication_records_newsletter_id_newsletters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publication_records'))
    )
    with op.batch_alter_table('publication_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_records_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_records_newsletter_id'), ['newsletter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_records_publication_status'), ['publication_status'], unique=False)

    op.create_table('review_sessions',
    sa.Column('newsletter_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('review_status', sa.Enum('pending', 'approved', 'changes_requested', 'rejected', name='review_status', native_enum=False, length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], name=op.f('fk_review_sessions_newsletter_id_newsletters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_sessions'))
    )
    with op.batch_alter_table('review_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_sessions_newsletter_id'), ['newsletter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_sessions_review_status'), ['review_status'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('newsletter_id', sa.Uuid(), nullable=True),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('workflow_status', sa.Enum('pending', 'running', 'success', 'failed', 'skipped', name='workflow_status', native_enum=False, length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], name=op.f('fk_workflow_runs_newsletter_id_newsletters'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs'))
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_newsletter_id'), ['newsletter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_workflow_name'), ['workflow_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_workflow_status'), ['workflow_status'], unique=False)

    op.create_table('agent_runs',
    sa.Column('workflow_run_id', sa.Uuid(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('execution_status', sa.Enum('pending', 'running', 'success', 'failed', 'skipped', name='agent_execution_status', native_enum=False, length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_agent_runs_workflow_run_id_workflow_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_execution_status'), ['execution_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('article_tags',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['collected_articles.id'], name=op.f('fk_article_tags_article_id_collected_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_tags')),
    sa.UniqueConstraint('article_id', 'tag_name', name='article_tag')
    )
    with op.batch_alter_table('article_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_tags_article_id'), ['article_id'], unique=False)

    op.create_table('feedback_items',
    sa.Column('review_session_id', sa.Uuid(), nullable=False),
    sa.Column('feedback_type', sa.Enum('rewrite', 'tone', 'factual', 'cut', 'add', 'general', name='feedback_type', native_enum=False, length=50), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('resolution_status', sa.Enum('open', 'in_progress', 'resolved', 'wont_fix', name='resolution_status', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], name=op.f('fk_feedback_items_review_session_id_review_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback_items'))
    )
    with op.batch_alter_table('feedback_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_items_resolution_status'), ['resolution_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_items_review_session_id'), ['review_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_items_review_session_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_items_resolution_status'))

    op.drop_table('feedback_items')
    with op.batch_alter_table('article_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_tags_article_id'))

    op.drop_table('article_tags')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_execution_status'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_name'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_workflow_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_workflow_name'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_newsletter_id'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('review_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_sessions_review_status'))
        batch_op.drop_index(batch_op.f('ix_review_sessions_newsletter_id'))

    op.drop_table('review_sessions')
    with op.batch_alter_table('publication_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_records_publication_status'))
        batch_op.drop_index(batch_op.f('ix_publication_records_newsletter_id'))
        batch_op.drop_index(batch_op.f('ix_publication_records_channel'))

    op.drop_table('publication_records')
    with op.batch_alter_table('newsletter_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_sections_newsletter_id'))

    op.drop_table('newsletter_sections')
    with op.batch_alter_table('generated_visuals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_visuals_newsletter_id'))

    op.drop_table('generated_visuals')
    with op.batch_alter_table('collected_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collected_articles_status'))
        batch_op.drop_index(batch_op.f('ix_collected_articles_source_id'))
        batch_op.drop_index(batch_op.f('ix_collected_articles_published_date'))
        batch_op.drop_index(batch_op.f('ix_collected_articles_content_hash'))
        batch_op.drop_index(batch_op.f('ix_collected_articles_category_id'))

    op.drop_table('collected_articles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletters_status'))
        batch_op.drop_index(batch_op.f('ix_newsletters_issue_number'))

    op.drop_table('newsletters')
    with op.batch_alter_table('content_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_sources_source_type'))
        batch_op.drop_index(batch_op.f('ix_content_sources_priority'))
        batch_op.drop_index(batch_op.f('ix_content_sources_is_active'))
        batch_op.drop_index(batch_op.f('ix_content_sources_category'))

    op.drop_table('content_sources')
    with op.batch_alter_table('article_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_categories_name'))

    op.drop_table('article_categories')
    # ### end Alembic commands ###
