"""add newsletter writer tables

Revision ID: 3b52036be01a
Revises: a7ee9c791efb
Create Date: 2026-06-18 11:22:07.459114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b52036be01a'
down_revision: Union[str, None] = 'a7ee9c791efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carousel_outlines',
    sa.Column('newsletter_id', sa.Uuid(), nullable=False),
    sa.Column('slides', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], name=op.f('fk_carousel_outlines_newsletter_id_newsletters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carousel_outlines'))
    )
    with op.batch_alter_table('carousel_outlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carousel_outlines_newsletter_id'), ['newsletter_id'], unique=False)

    op.create_table('linkedin_posts',
    sa.Column('newsletter_id', sa.Uuid(), nullable=False),
    sa.Column('variant', sa.String(length=50), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], name=op.f('fk_linkedin_posts_newsletter_id_newsletters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_linkedin_posts'))
    )
    with op.batch_alter_table('linkedin_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_linkedin_posts_newsletter_id'), ['newsletter_id'], unique=False)

    op.create_table('newsletter_drafts',
    sa.Column('newsletter_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('email_subjects', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('generation_time_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], name=op.f('fk_newsletter_drafts_newsletter_id_newsletters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_drafts'))
    )
    with op.batch_alter_table('newsletter_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_drafts_newsletter_id'), ['newsletter_id'], unique=True)

    op.create_table('newsletter_versions',
    sa.Column('newsletter_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], name=op.f('fk_newsletter_versions_newsletter_id_newsletters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_versions')),
    sa.UniqueConstraint('newsletter_id', 'version_number', name='version')
    )
    with op.batch_alter_table('newsletter_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_versions_newsletter_id'), ['newsletter_id'], unique=False)

    op.create_table('regeneration_history',
    sa.Column('newsletter_id', sa.Uuid(), nullable=False),
    sa.Column('section_name', sa.String(length=80), nullable=False),
    sa.Column('from_version', sa.Integer(), nullable=True),
    sa.Column('to_version', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], name=op.f('fk_regeneration_history_newsletter_id_newsletters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regeneration_history'))
    )
    with op.batch_alter_table('regeneration_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regeneration_history_newsletter_id'), ['newsletter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regeneration_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regeneration_history_newsletter_id'))

    op.drop_table('regeneration_history')
    with op.batch_alter_table('newsletter_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_versions_newsletter_id'))

    op.drop_table('newsletter_versions')
    with op.batch_alter_table('newsletter_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_drafts_newsletter_id'))

    op.drop_table('newsletter_drafts')
    with op.batch_alter_table('linkedin_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linkedin_posts_newsletter_id'))

    op.drop_table('linkedin_posts')
    with op.batch_alter_table('carousel_outlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carousel_outlines_newsletter_id'))

    op.drop_table('carousel_outlines')
    # ### end Alembic commands ###
