"""add publishing tables and fields

Revision ID: a6ce37c3a532
Revises: 11f44247c0d5
Create Date: 2026-06-18 22:18:35.823064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ce37c3a532'
down_revision: Union[str, None] = '11f44247c0d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'unsubscribed', 'bounced', name='subscriber_status', native_enum=False, length=50), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscribers'))
    )
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscribers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_subscribers_status'), ['status'], unique=False)

    op.create_table('publication_analytics',
    sa.Column('newsletter_id', sa.Uuid(), nullable=False),
    sa.Column('publication_record_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('click_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('impressions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('engagement', sa.Float(), server_default='0', nullable=False),
    sa.Column('subscriber_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('growth_metrics', sa.JSON(), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], name=op.f('fk_publication_analytics_newsletter_id_newsletters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_record_id'], ['publication_records.id'], name=op.f('fk_publication_analytics_publication_record_id_publication_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publication_analytics'))
    )
    with op.batch_alter_table('publication_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_analytics_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_analytics_newsletter_id'), ['newsletter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_analytics_publication_record_id'), ['publication_record_id'], unique=False)

    op.create_table('publication_failures',
    sa.Column('publication_record_id', sa.Uuid(), nullable=True),
    sa.Column('newsletter_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('error_type', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], name=op.f('fk_publication_failures_newsletter_id_newsletters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_record_id'], ['publication_records.id'], name=op.f('fk_publication_failures_publication_record_id_publication_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publication_failures'))
    )
    with op.batch_alter_table('publication_failures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_failures_newsletter_id'), ['newsletter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_failures_publication_record_id'), ['publication_record_id'], unique=False)

    op.create_table('retry_queue',
    sa.Column('publication_record_id', sa.Uuid(), nullable=False),
    sa.Column('newsletter_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='3', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], name=op.f('fk_retry_queue_newsletter_id_newsletters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_record_id'], ['publication_records.id'], name=op.f('fk_retry_queue_publication_record_id_publication_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retry_queue'))
    )
    with op.batch_alter_table('retry_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retry_queue_newsletter_id'), ['newsletter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retry_queue_publication_record_id'), ['publication_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retry_queue_status'), ['status'], unique=False)

    with op.batch_alter_table('publication_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publish_state', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('external_publication_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('channel_metadata', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_publication_records_publish_state'), ['publish_state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_records_publish_state'))
        batch_op.drop_column('channel_metadata')
        batch_op.drop_column('last_retry_at')
        batch_op.drop_column('error_message')
        batch_op.drop_column('retry_count')
        batch_op.drop_column('external_publication_id')
        batch_op.drop_column('publish_state')

    with op.batch_alter_table('retry_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retry_queue_status'))
        batch_op.drop_index(batch_op.f('ix_retry_queue_publication_record_id'))
        batch_op.drop_index(batch_op.f('ix_retry_queue_newsletter_id'))

    op.drop_table('retry_queue')
    with op.batch_alter_table('publication_failures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_failures_publication_record_id'))
        batch_op.drop_index(batch_op.f('ix_publication_failures_newsletter_id'))

    op.drop_table('publication_failures')
    with op.batch_alter_table('publication_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_analytics_publication_record_id'))
        batch_op.drop_index(batch_op.f('ix_publication_analytics_newsletter_id'))
        batch_op.drop_index(batch_op.f('ix_publication_analytics_channel'))

    op.drop_table('publication_analytics')
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribers_status'))
        batch_op.drop_index(batch_op.f('ix_subscribers_email'))

    op.drop_table('subscribers')
    # ### end Alembic commands ###
