"""add fact checking tables and fields

Revision ID: a7ee9c791efb
Revises: b9bfa95ced5f
Create Date: 2026-06-18 09:58:37.932973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ee9c791efb'
down_revision: Union[str, None] = 'b9bfa95ced5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieval_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['collected_articles.id'], name=op.f('fk_citations_article_id_collected_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citations'))
    )
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citations_article_id'), ['article_id'], unique=False)

    op.create_table('evidence_packages',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=True),
    sa.Column('supporting_sources', sa.JSON(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('package', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['collected_articles.id'], name=op.f('fk_evidence_packages_article_id_collected_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_packages'))
    )
    with op.batch_alter_table('evidence_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_packages_article_id'), ['article_id'], unique=True)

    op.create_table('fact_check_results',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('url_accessible', sa.Boolean(), nullable=True),
    sa.Column('source_credibility_score', sa.Float(), nullable=True),
    sa.Column('claim_verification_score', sa.Float(), nullable=True),
    sa.Column('cross_source_score', sa.Float(), nullable=True),
    sa.Column('freshness_score', sa.Float(), nullable=True),
    sa.Column('evidence_score', sa.Float(), nullable=True),
    sa.Column('overall_confidence_score', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=True),
    sa.Column('fact_check_notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['collected_articles.id'], name=op.f('fk_fact_check_results_article_id_collected_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_check_results'))
    )
    with op.batch_alter_table('fact_check_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_check_results_article_id'), ['article_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_fact_check_results_overall_confidence_score'), ['overall_confidence_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_check_results_verification_status'), ['verification_status'], unique=False)

    op.create_table('verified_claims',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=40), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=True),
    sa.Column('support_score', sa.Float(), nullable=True),
    sa.Column('corroborating_sources', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['collected_articles.id'], name=op.f('fk_verified_claims_article_id_collected_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verified_claims'))
    )
    with op.batch_alter_table('verified_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verified_claims_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verified_claims_verification_status'), ['verification_status'], unique=False)

    with op.batch_alter_table('collected_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('overall_confidence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_collected_articles_verification_status'), ['verification_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collected_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collected_articles_verification_status'))
        batch_op.drop_column('verified_at')
        batch_op.drop_column('overall_confidence_score')
        batch_op.drop_column('verification_status')

    with op.batch_alter_table('verified_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verified_claims_verification_status'))
        batch_op.drop_index(batch_op.f('ix_verified_claims_article_id'))

    op.drop_table('verified_claims')
    with op.batch_alter_table('fact_check_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_check_results_verification_status'))
        batch_op.drop_index(batch_op.f('ix_fact_check_results_overall_confidence_score'))
        batch_op.drop_index(batch_op.f('ix_fact_check_results_article_id'))

    op.drop_table('fact_check_results')
    with op.batch_alter_table('evidence_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_packages_article_id'))

    op.drop_table('evidence_packages')
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citations_article_id'))

    op.drop_table('citations')
    # ### end Alembic commands ###
