"""add relevance and categorization fields

Revision ID: b9bfa95ced5f
Revises: 250f42812eb5
Create Date: 2026-06-17 15:17:52.634030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9bfa95ced5f'
down_revision: Union[str, None] = '250f42812eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collected_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newsletter_relevance_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('technical_depth_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('enterprise_value_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('qa_value_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trend_signal_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overall_relevance_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('canonical_story_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('primary_category', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('secondary_category', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('topics', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ranking_position', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_selected', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_collected_articles_canonical_story_id'), ['canonical_story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collected_articles_is_selected'), ['is_selected'], unique=False)
        batch_op.create_index(batch_op.f('ix_collected_articles_overall_relevance_score'), ['overall_relevance_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_collected_articles_ranking_position'), ['ranking_position'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collected_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collected_articles_ranking_position'))
        batch_op.drop_index(batch_op.f('ix_collected_articles_overall_relevance_score'))
        batch_op.drop_index(batch_op.f('ix_collected_articles_is_selected'))
        batch_op.drop_index(batch_op.f('ix_collected_articles_canonical_story_id'))
        batch_op.drop_column('is_selected')
        batch_op.drop_column('ranking_position')
        batch_op.drop_column('keywords')
        batch_op.drop_column('topics')
        batch_op.drop_column('secondary_category')
        batch_op.drop_column('primary_category')
        batch_op.drop_column('canonical_story_id')
        batch_op.drop_column('overall_relevance_score')
        batch_op.drop_column('trend_signal_score')
        batch_op.drop_column('qa_value_score')
        batch_op.drop_column('enterprise_value_score')
        batch_op.drop_column('technical_depth_score')
        batch_op.drop_column('newsletter_relevance_score')

    # ### end Alembic commands ###
